# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotificationServiceExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationServiceExtension
    pod ‘pyze-iOS-extensions’
end

target 'Pyze_Rich_Interactive_Push_SampleApp_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pyze_Rich_Interactive_Push_SampleApp_Swift
   pod ‘pyze-sdk-iOS’
end
