# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MessagesExtension' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MessagesExtension

  pod 'pyze-sdk-iOS'

end

target 'PyzeIMessageApps' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PyzeIMessageApps

  pod 'pyze-sdk-iOS'

end
