# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'
use_frameworks!

target 'SwiftExampleWithCocoapods' do
pod 'pyze-sdk-iOS', '1.6.0'
end

