# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TestCocoapods' do
pod 'pyze-sdk-iOS', '1.6.0'

end

