# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestOneMore' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestOneMore
pod 'pyze-sdk-iOS'

end

target 'WatchTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WatchTest

end

target 'WatchTest Extension' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WatchTest Extension

end
