# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotificationServiceExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NotificationServiceExtension
   pod ‘pyze-iOS-extensions’

end

target 'Pyze_Rich_Interactive_Push_SampleApp_ObjectiveC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pyze_Rich_Interactive_Push_SampleApp_ObjectiveC
    pod ‘pyze-sdk-iOS’
end
